//! Global state managed by the Raft state machine.
//!
//! This is the authoritative state of the cluster, replicated across all quorum members.
//! Strong consistency for: node ownership, sensitive audit log.
//! Eventually consistent data (telemetry, metrics) is NOT stored here per ADR-004.

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use ed25519_dalek::{Signer, SigningKey, Verifier, VerifyingKey};
use lattice_common::error::LatticeError;
use lattice_common::traits::{AuditEntry, AuditFilter};
use lattice_common::types::{
    AllocId, Allocation, AllocationState, CompletionPhase, IsolationLevel, NetworkDomain,
    NetworkDomainState, Node, NodeId, NodeOwnership, NodeState, RegisteredEndpoint,
    ServiceRegistryEntry, Session, SessionId, Tenant, TenantId, TenantQuota, TopologyModel,
    VCluster, VClusterId,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::commands::{Command, CommandResponse};
use crate::TypeConfig;

/// INV-D7: numeric rank of a CompletionPhase for monotonic ordering.
/// Used by per-node phase-regression check in `apply_completion_report`.
/// The aggregate `AllocationState` is derived from `per_node_phase`, not
/// compared directly against incoming phases, so state_rank is unused.
fn phase_rank(p: CompletionPhase) -> u8 {
    match p {
        CompletionPhase::Staging => 1,
        CompletionPhase::Running => 2,
        CompletionPhase::Completed => 3,
        CompletionPhase::Failed => 3,
    }
}

/// Metadata about an archived chunk of audit log entries stored in external storage (S3).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditArchive {
    /// S3 object key where the archived entries are stored.
    pub object_key: String,
    /// Number of entries in this archive chunk.
    pub entry_count: usize,
    /// Timestamp of the first entry in the chunk.
    pub first_timestamp: DateTime<Utc>,
    /// Timestamp of the last entry in the chunk.
    pub last_timestamp: DateTime<Utc>,
    /// SHA-256 hash of the last entry in the chunk (for chain continuity).
    pub last_entry_hash: String,
}

fn default_audit_retention() -> usize {
    10_000
}

fn default_signing_key() -> SigningKey {
    SigningKey::generate(&mut rand_core::OsRng)
}

/// The complete cluster state replicated via Raft.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlobalState {
    pub nodes: HashMap<NodeId, Node>,
    pub allocations: HashMap<AllocId, Allocation>,
    pub tenants: HashMap<TenantId, Tenant>,
    pub vclusters: HashMap<VClusterId, VCluster>,
    pub topology: TopologyModel,
    pub audit_log: Vec<AuditEntry>,
    /// Maximum number of audit entries to keep in Raft state.
    /// Older entries are archived during compaction. Default: 10,000.
    #[serde(default = "default_audit_retention")]
    pub audit_retention_limit: usize,
    /// Archived audit log summaries — pointers to S3 objects containing older entries.
    /// Each archive chunk covers a time range and stores the last entry's hash for chain continuity.
    #[serde(default)]
    pub audit_archives: Vec<AuditArchive>,
    /// System-wide limit on nodes that can be claimed for sensitive use.
    /// None means unlimited (no sensitive pool cap).
    pub sensitive_pool_size: Option<u32>,
    /// Monotonic version counter. Incremented on every state mutation.
    /// Used by the scheduler for optimistic concurrency control (ADV-04).
    #[serde(default)]
    pub state_version: u64,
    /// Network domains keyed by (tenant, name) for tenant-scoped uniqueness (ADV-09).
    #[serde(default)]
    pub network_domains: HashMap<String, NetworkDomain>,
    /// VNI pool: tracks allocated VNIs for authoritative management (ADV-08).
    #[serde(default)]
    pub vni_pool: VniPool,
    /// Service registry: maps service name → registered endpoints.
    /// Updated automatically when allocations with `expose` endpoints
    /// transition to Running (register) or terminal states (deregister).
    #[serde(default)]
    pub service_registry: HashMap<String, ServiceRegistryEntry>,
    /// Active sessions tracked globally for session limit enforcement (F20).
    #[serde(default)]
    pub sessions: HashMap<SessionId, Session>,
    /// Ed25519 signing key for audit log entries. Not serialized into Raft snapshots —
    /// keys are loaded from site configuration on startup, not replicated via consensus.
    /// A fresh random key is generated by Default for testing; production deployments
    /// must call `set_signing_key()` with the site's persistent key.
    #[serde(skip, default = "default_signing_key")]
    pub audit_signing_key: SigningKey,
}

/// Authoritative VNI pool allocator (ADV-08).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VniPool {
    /// Start of the VNI range (inclusive).
    pub start: u32,
    /// End of the VNI range (inclusive).
    pub end: u32,
    /// Currently allocated VNIs (value = domain key "tenant/name").
    pub allocated: HashMap<u32, String>,
    /// Next candidate VNI to try (F19: avoids O(n) linear scan).
    #[serde(default)]
    pub next_candidate: u32,
}

impl Default for VniPool {
    fn default() -> Self {
        Self {
            start: 100,
            end: 4095,
            allocated: HashMap::new(),
            next_candidate: 100,
        }
    }
}

impl VniPool {
    /// Allocate the next available VNI. Returns None if pool is exhausted.
    pub fn allocate(&mut self, domain_key: &str) -> Option<u32> {
        // Start from next_candidate for O(1) amortized allocation
        for vni in self.next_candidate..=self.end {
            if let std::collections::hash_map::Entry::Vacant(e) = self.allocated.entry(vni) {
                e.insert(domain_key.to_string());
                self.next_candidate = vni + 1;
                return Some(vni);
            }
        }
        // Wrap around to start
        for vni in self.start..self.next_candidate {
            if let std::collections::hash_map::Entry::Vacant(e) = self.allocated.entry(vni) {
                e.insert(domain_key.to_string());
                self.next_candidate = vni + 1;
                return Some(vni);
            }
        }
        None
    }

    /// Release a VNI back to the pool.
    pub fn release(&mut self, vni: u32) {
        self.allocated.remove(&vni);
    }
}

impl Default for GlobalState {
    fn default() -> Self {
        Self {
            nodes: HashMap::new(),
            allocations: HashMap::new(),
            tenants: HashMap::new(),
            vclusters: HashMap::new(),
            topology: TopologyModel { groups: vec![] },
            audit_log: Vec::new(),
            audit_retention_limit: default_audit_retention(),
            audit_archives: Vec::new(),
            sensitive_pool_size: None,
            state_version: 0,
            network_domains: HashMap::new(),
            vni_pool: VniPool::default(),
            service_registry: HashMap::new(),
            sessions: HashMap::new(),
            audit_signing_key: SigningKey::generate(&mut rand_core::OsRng),
        }
    }
}

impl GlobalState {
    pub fn new() -> Self {
        Self::default()
    }

    /// Load signing key from a 32-byte seed (from SecretResolver).
    pub fn load_signing_key_from_bytes(&mut self, seed: &[u8; 32]) -> Result<(), String> {
        self.audit_signing_key = SigningKey::from_bytes(seed);
        Ok(())
    }

    /// Load signing key from a 32-byte seed file (F10).
    /// Returns Ok(()) if loaded, Err if file missing or invalid.
    pub fn load_signing_key_from_file(&mut self, path: &std::path::Path) -> Result<(), String> {
        let bytes = std::fs::read(path)
            .map_err(|e| format!("failed to read signing key from {}: {e}", path.display()))?;
        if bytes.len() < 32 {
            return Err(format!(
                "signing key file must be at least 32 bytes, got {}",
                bytes.len()
            ));
        }
        let seed: [u8; 32] = bytes[..32]
            .try_into()
            .map_err(|_| "failed to extract 32-byte seed".to_string())?;
        self.audit_signing_key = SigningKey::from_bytes(&seed);
        Ok(())
    }

    /// Apply a command to the state machine, returning a response.
    pub fn apply(&mut self, cmd: Command) -> CommandResponse {
        let resp = match cmd {
            Command::SubmitAllocation(alloc) => self.submit_allocation(alloc),
            Command::UpdateAllocationState {
                id,
                state,
                message,
                exit_code,
            } => self.update_allocation_state(id, state, message, exit_code),
            Command::AssignNodes {
                id,
                nodes,
                expected_version,
            } => self.assign_nodes(id, nodes, expected_version),
            Command::RequeueAllocation {
                id,
                expected_requeue_count,
            } => self.requeue_allocation(id, expected_requeue_count),
            Command::RegisterNode(node) => self.register_node(node),
            Command::UpdateNodeState { id, state, reason } => {
                self.update_node_state(id, state, reason)
            }
            Command::ClaimNode { id, ownership } => self.claim_node(id, ownership),
            Command::ReleaseNode { id } => self.release_node(id),
            Command::RecordHeartbeat {
                id,
                timestamp,
                owner_version,
                reattach_in_progress,
            } => self.record_heartbeat(id, timestamp, owner_version, reattach_in_progress),
            Command::UpdateNodeAddress {
                node_id,
                new_address,
            } => self.update_node_address(node_id, new_address),
            Command::ApplyCompletionReport {
                node_id,
                allocation_id,
                phase,
                pid,
                exit_code,
                reason,
            } => {
                self.apply_completion_report(node_id, allocation_id, phase, pid, exit_code, reason)
            }
            Command::RollbackDispatch {
                allocation_id,
                released_nodes,
                failed_node,
                observed_state_version,
                reason,
            } => self.rollback_dispatch(
                allocation_id,
                released_nodes,
                failed_node,
                observed_state_version,
                reason,
            ),
            Command::ProbeReleaseDegradedNode {
                node_id,
                expected_degraded_at,
            } => self.probe_release_degraded_node(node_id, expected_degraded_at),
            Command::CreateTenant(tenant) => self.create_tenant(tenant),
            Command::UpdateTenant {
                id,
                quota,
                isolation_level,
            } => self.update_tenant(id, quota, isolation_level),
            Command::CreateVCluster(vc) => self.create_vcluster(vc),
            Command::UpdateVCluster {
                id,
                cost_weights,
                allow_borrowing,
                allow_lending,
            } => self.update_vcluster(id, cost_weights, allow_borrowing, allow_lending),
            Command::UpdateTopology(topo) => {
                self.topology = topo;
                CommandResponse::Ok
            }
            Command::SetSensitivePoolSize(size) => {
                self.sensitive_pool_size = size;
                CommandResponse::Ok
            }
            Command::CreateNetworkDomain { tenant, name } => {
                self.create_network_domain(tenant, name)
            }
            Command::ReleaseNetworkDomain { tenant, name } => {
                self.release_network_domain(tenant, name)
            }
            Command::ResolveImage {
                id,
                image_index,
                resolved,
            } => self.resolve_image(id, image_index, resolved),
            Command::CreateSession(session) => self.create_session(session),
            Command::DeleteSession { session_id } => self.delete_session(session_id),
            Command::RecordAudit(entry) => self.record_audit(entry),
            Command::CompactAuditLog {
                object_key,
                entries_to_archive,
            } => self.compact_audit_log(object_key, entries_to_archive),
        };
        // Increment state version on every successful mutation (ADV-04).
        if !matches!(resp, CommandResponse::Error(_)) {
            self.state_version += 1;
        }
        resp
    }

    // ── Allocation operations ───────────────────────────────

    fn submit_allocation(&mut self, alloc: Allocation) -> CommandResponse {
        // Hard quota check
        if let Err(e) = self.check_hard_quota(&alloc) {
            return CommandResponse::Error(e.to_string());
        }

        let id = alloc.id;
        self.allocations.insert(id, alloc);
        CommandResponse::AllocationId(id)
    }

    fn update_allocation_state(
        &mut self,
        id: AllocId,
        new_state: AllocationState,
        message: Option<String>,
        exit_code: Option<i32>,
    ) -> CommandResponse {
        let Some(alloc) = self.allocations.get_mut(&id) else {
            return CommandResponse::Error(format!("Allocation not found: {id}"));
        };

        if !alloc.state.can_transition_to(&new_state) {
            return CommandResponse::Error(format!(
                "Invalid transition from {:?} to {:?}",
                alloc.state, new_state
            ));
        }

        alloc.state = new_state.clone();
        if let Some(msg) = message {
            alloc.message = Some(msg);
        }
        if let Some(code) = exit_code {
            alloc.exit_code = Some(code);
        }

        // Update timestamps
        match new_state {
            AllocationState::Running => {
                alloc.started_at = Some(Utc::now());
            }
            AllocationState::Completed | AllocationState::Failed | AllocationState::Cancelled => {
                alloc.completed_at = Some(Utc::now());
            }
            _ => {}
        }

        // Service endpoint registration/deregistration
        let expose = alloc.connectivity.expose.clone();
        let tenant = alloc.tenant.clone();
        let nodes = alloc.assigned_nodes.clone();
        match &alloc.state {
            AllocationState::Running if !expose.is_empty() => {
                for ep in &expose {
                    let entry = self.service_registry.entry(ep.name.clone()).or_default();
                    // Avoid duplicate registrations for the same allocation
                    if !entry.endpoints.iter().any(|e| e.allocation_id == id) {
                        entry.endpoints.push(RegisteredEndpoint {
                            allocation_id: id,
                            tenant: tenant.clone(),
                            nodes: nodes.clone(),
                            port: ep.port,
                            protocol: ep.protocol.clone(),
                        });
                    }
                }
            }
            s if s.is_terminal() && !expose.is_empty() => {
                for ep in &expose {
                    if let Some(entry) = self.service_registry.get_mut(&ep.name) {
                        entry.endpoints.retain(|e| e.allocation_id != id);
                        // Remove empty entries to keep registry clean
                    }
                }
                self.service_registry.retain(|_, v| !v.endpoints.is_empty());
            }
            _ => {}
        }

        CommandResponse::Ok
    }

    fn assign_nodes(
        &mut self,
        id: AllocId,
        nodes: Vec<NodeId>,
        expected_version: Option<u64>,
    ) -> CommandResponse {
        // Optimistic concurrency check (ADV-04).
        if let Some(ev) = expected_version {
            if ev != self.state_version {
                return CommandResponse::Error(format!(
                    "Stale proposal: expected state version {ev}, current is {}. Retry with fresh state.",
                    self.state_version
                ));
            }
        }
        let Some(alloc) = self.allocations.get(&id) else {
            return CommandResponse::Error(format!("Allocation not found: {id}"));
        };
        let tenant_id = alloc.tenant.clone();
        let new_node_count = nodes.len() as u32;

        // Re-check tenant max_nodes quota before assigning
        if let Some(tenant) = self.tenants.get(&tenant_id) {
            let other_nodes_in_use: u32 = self
                .allocations
                .iter()
                .filter(|(aid, a)| **aid != id && a.tenant == tenant_id && !a.state.is_terminal())
                .map(|(_, a)| a.assigned_nodes.len() as u32)
                .sum();

            if other_nodes_in_use + new_node_count > tenant.quota.max_nodes {
                return CommandResponse::Error(format!(
                    "Quota exceeded for tenant {}: max_nodes ({}) would be exceeded: \
                     {} in use by other allocations + {} to assign",
                    tenant_id, tenant.quota.max_nodes, other_nodes_in_use, new_node_count
                ));
            }
        }

        let Some(alloc) = self.allocations.get_mut(&id) else {
            return CommandResponse::Error(format!("Allocation vanished during assign: {id}"));
        };
        alloc.assigned_nodes = nodes;
        // D-ADV-IMPL-07 fix: record when the allocation was placed, so
        // the silent-sweep fresh-allocation exemption uses the correct
        // timestamp rather than the much-older submission timestamp.
        alloc.assigned_at = Some(Utc::now());
        CommandResponse::Ok
    }

    fn resolve_image(
        &mut self,
        id: AllocId,
        image_index: usize,
        resolved: lattice_common::types::ImageRef,
    ) -> CommandResponse {
        let Some(alloc) = self.allocations.get_mut(&id) else {
            return CommandResponse::Error(format!("Allocation not found: {id}"));
        };

        if image_index >= alloc.environment.images.len() {
            return CommandResponse::Error(format!(
                "Image index {image_index} out of bounds (allocation has {} images)",
                alloc.environment.images.len()
            ));
        }

        let img = &mut alloc.environment.images[image_index];
        img.sha256 = resolved.sha256;
        img.size_bytes = resolved.size_bytes;
        img.registry = resolved.registry;
        img.name = resolved.name;
        img.version = resolved.version;
        img.resolve_on_schedule = false;
        CommandResponse::Ok
    }

    fn requeue_allocation(
        &mut self,
        id: AllocId,
        expected_requeue_count: Option<u32>,
    ) -> CommandResponse {
        let Some(alloc) = self.allocations.get_mut(&id) else {
            return CommandResponse::Error(format!("Allocation not found: {id}"));
        };

        // F14: Optimistic concurrency — reject if count changed
        if let Some(expected) = expected_requeue_count {
            if alloc.requeue_count != expected {
                return CommandResponse::Error(format!(
                    "Requeue conflict: expected count {expected}, actual {}",
                    alloc.requeue_count
                ));
            }
        }

        if !alloc.state.can_transition_to(&AllocationState::Pending) {
            return CommandResponse::Error(format!("Cannot requeue from {:?}", alloc.state));
        }

        if alloc.requeue_count >= alloc.max_requeue {
            return CommandResponse::Error(format!(
                "Max requeue limit reached ({}/{})",
                alloc.requeue_count, alloc.max_requeue
            ));
        }

        // Deregister service endpoints before resetting state
        let expose = alloc.connectivity.expose.clone();
        for ep in &expose {
            if let Some(entry) = self.service_registry.get_mut(&ep.name) {
                entry.endpoints.retain(|e| e.allocation_id != id);
            }
        }
        self.service_registry.retain(|_, v| !v.endpoints.is_empty());

        alloc.state = AllocationState::Pending;
        alloc.requeue_count += 1;
        alloc.assigned_nodes.clear();
        alloc.started_at = None;
        alloc.completed_at = None;
        alloc.exit_code = None;
        alloc.message = None;
        // INT-2: clear dispatch-specific fields so the next placement sees a
        // clean slate. Without this, a requeue carries stale per_node_phase
        // into its next dispatch (ApplyCompletionReport would aggregate over
        // OLD nodes + the newly assigned ones), assigned_at would still
        // point at the previous placement time (silent-sweep fresh-exemption
        // would be wrong), dispatch_retry_count would accumulate across
        // requeues (a long-running service with occasional node failures
        // would eventually hit max_dispatch_retries and go to Failed
        // permanently), and last_completion_report_at would make the
        // Dispatcher think the new placement has already been ack'd.
        alloc.per_node_phase.clear();
        alloc.assigned_at = None;
        alloc.dispatch_retry_count = 0;
        alloc.last_completion_report_at = None;
        CommandResponse::Ok
    }

    // ── Session operations (F20) ──────────────────────────────

    fn create_session(&mut self, session: Session) -> CommandResponse {
        let alloc_id = session.allocation_id;

        // Verify allocation exists and is Running
        let Some(alloc) = self.allocations.get(&alloc_id) else {
            return CommandResponse::Error(format!("Allocation not found: {alloc_id}"));
        };
        if alloc.state != AllocationState::Running {
            return CommandResponse::Error(format!(
                "Allocation {alloc_id} is {:?}, not Running",
                alloc.state
            ));
        }

        // Enforce global session limit for sensitive allocations (INV-C2)
        if alloc.sensitive {
            let existing = self
                .sessions
                .values()
                .filter(|s| s.allocation_id == alloc_id)
                .count();
            if existing >= 1 {
                return CommandResponse::Error(format!(
                    "Sensitive allocation {alloc_id} already has an active session (INV-C2)"
                ));
            }
        }

        let id = session.id;
        self.sessions.insert(id, session);
        CommandResponse::SessionId(id)
    }

    fn delete_session(&mut self, session_id: SessionId) -> CommandResponse {
        if self.sessions.remove(&session_id).is_none() {
            return CommandResponse::Error(format!("Session not found: {session_id}"));
        }
        CommandResponse::Ok
    }

    // ── Node operations ─────────────────────────────────────

    fn register_node(&mut self, node: Node) -> CommandResponse {
        let id = node.id.clone();
        self.nodes.insert(id.clone(), node);
        CommandResponse::NodeId(id)
    }

    fn update_node_state(
        &mut self,
        id: NodeId,
        new_state: NodeState,
        reason: Option<String>,
    ) -> CommandResponse {
        let Some(node) = self.nodes.get_mut(&id) else {
            return CommandResponse::Error(format!("Node not found: {id}"));
        };

        if !node.state.can_transition_to(&new_state) {
            return CommandResponse::Error(format!(
                "Invalid node transition from {:?} to {:?}",
                node.state, new_state
            ));
        }

        node.state = new_state;
        let _ = reason; // Could store in a reason field if needed
        CommandResponse::Ok
    }

    fn claim_node(&mut self, id: NodeId, ownership: NodeOwnership) -> CommandResponse {
        // Check node exists and ownership conflict (immutable borrows first)
        {
            let Some(node) = self.nodes.get(&id) else {
                return CommandResponse::Error(format!("Node not found: {id}"));
            };
            if let Some(ref existing) = node.owner {
                if existing.claimed_by.is_some() && ownership.claimed_by.is_some() {
                    return CommandResponse::Error(format!(
                        "Node {id} already claimed by {}",
                        existing.claimed_by.as_deref().unwrap_or("unknown")
                    ));
                }
            }
        }

        // Check sensitive_pool_size limit if this is a sensitive claim
        if ownership.claimed_by.is_some() {
            if let Some(pool_limit) = self.sensitive_pool_size {
                let currently_claimed = self
                    .nodes
                    .values()
                    .filter(|n| {
                        n.owner
                            .as_ref()
                            .map(|o| o.claimed_by.is_some())
                            .unwrap_or(false)
                    })
                    .count() as u32;

                if currently_claimed >= pool_limit {
                    return CommandResponse::Error(format!(
                        "sensitive_pool_size limit ({}) reached: {} nodes already claimed",
                        pool_limit, currently_claimed
                    ));
                }
            }
        }

        let Some(node) = self.nodes.get_mut(&id) else {
            return CommandResponse::Error(format!("Node vanished during claim: {id}"));
        };
        node.owner = Some(ownership);
        node.owner_version += 1; // ADV-06: bump on ownership change
        CommandResponse::Ok
    }

    fn release_node(&mut self, id: NodeId) -> CommandResponse {
        let Some(node) = self.nodes.get_mut(&id) else {
            return CommandResponse::Error(format!("Node not found: {id}"));
        };
        node.owner = None;
        node.owner_version += 1; // ADV-06: bump on ownership change
        CommandResponse::Ok
    }

    fn record_heartbeat(
        &mut self,
        id: NodeId,
        timestamp: DateTime<Utc>,
        owner_version: u64,
        reattach_in_progress: bool,
    ) -> CommandResponse {
        let Some(node) = self.nodes.get_mut(&id) else {
            return CommandResponse::Error(format!("Node not found: {id}"));
        };
        // ADV-06: reject heartbeats from stale owner contexts.
        if owner_version != node.owner_version {
            return CommandResponse::Error(format!(
                "Stale heartbeat for node {id}: owner_version {owner_version} != current {}",
                node.owner_version
            ));
        }
        node.last_heartbeat = Some(timestamp);

        // INV-D5 flag lifecycle (DEC-DISP-03 / DEC-DISP-10 / D-ADV-ARCH-06):
        //   1. The flag may only transition false → true on the first
        //      heartbeat following a fresh RegisterNode / UpdateNodeAddress
        //      (we cannot observe that here, but the first true-valued
        //      heartbeat since the node had no prior first_set_at is the
        //      proxy). Once set, reattach_first_set_at is the absolute
        //      grace-window start.
        //   2. Subsequent true-valued heartbeats during the grace window do
        //      NOT reset the timer.
        //   3. Set to false is one-way within a registration lifetime: once
        //      cleared, the flag cannot return to true without a fresh
        //      RegisterNode (which resets first_set_at).
        //   4. After `reattach_grace_period` has elapsed since
        //      reattach_first_set_at, INV-D8 treats the flag as false
        //      regardless of its recorded value. Enforcement of that
        //      deadline lives in the silent-sweep consumer, not here.
        match (node.reattach_in_progress, reattach_in_progress) {
            (false, true) => {
                if node.reattach_first_set_at.is_none() {
                    node.reattach_in_progress = true;
                    node.reattach_first_set_at = Some(timestamp);
                }
                // Rule 3: once cleared, cannot return to true.
            }
            (true, true) => {
                // No-op: flag already set; do not reset timer.
            }
            (true, false) => {
                // One-way clear: leave first_set_at in place so the
                // lifecycle remains observable.
                node.reattach_in_progress = false;
            }
            (false, false) => {
                // No-op.
            }
        }

        CommandResponse::Ok
    }

    // ── Dispatch command handlers (INV-D1, INV-D4/D6/D7/D11/D12) ────────

    fn update_node_address(&mut self, node_id: NodeId, new_address: String) -> CommandResponse {
        // Syntactic invariants are checked at the API layer (INV-D1); this
        // apply-step re-validates that the address is non-empty as a
        // defense-in-depth against crafted proposals.
        if new_address.trim().is_empty() {
            return CommandResponse::Error("agent_address_required".into());
        }
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return CommandResponse::Error(format!("Node not found: {node_id}"));
        };
        if node.agent_address == new_address {
            return CommandResponse::Ok;
        }
        node.agent_address = new_address;
        // Re-registration semantics: a new address is observable like a
        // fresh registration, so reset the reattach lifecycle tracker.
        node.reattach_in_progress = false;
        node.reattach_first_set_at = None;
        CommandResponse::Ok
    }

    fn apply_completion_report(
        &mut self,
        node_id: NodeId,
        allocation_id: AllocId,
        phase: CompletionPhase,
        pid: Option<u32>,
        exit_code: Option<i32>,
        reason: Option<String>,
    ) -> CommandResponse {
        let Some(alloc) = self.allocations.get_mut(&allocation_id) else {
            return CommandResponse::Error(format!("Allocation not found: {allocation_id}"));
        };

        // INV-D12 source-auth: reporting node must be assigned to this allocation.
        if !alloc.assigned_nodes.contains(&node_id) {
            lattice_common::metrics::record_cross_node_report(&node_id);
            return CommandResponse::Error(format!(
                "cross_node_report: {node_id} not in assigned_nodes for {allocation_id}"
            ));
        }

        // INV-D7 monotonicity + INV-D4 idempotency are applied at the
        // per-node granularity below, because DEC-DISP-11 requires per-node
        // tracking: aggregate `alloc.state` is a derived function of
        // `per_node_phase`, not an independent variable. The aggregate
        // cannot regress under the rules in use without a separate cancel
        // or rollback command.
        //
        // Per-node phase tracking (DEC-DISP-11 conservative aggregation).
        // Apply INV-D7 monotonicity at the per-node level, not just the
        // aggregated level: a node's own phase must advance monotonically,
        // else reject. Fix for D-ADV-IMPL-06.
        if let Some(&prev_phase) = alloc.per_node_phase.get(&node_id) {
            if phase_rank(phase) < phase_rank(prev_phase) {
                lattice_common::metrics::record_phase_regression(
                    &format!("{prev_phase:?}"),
                    &format!("{phase:?}"),
                );
                return CommandResponse::Error(format!(
                    "phase_regression_per_node: {node_id} current {prev_phase:?} vs reported {phase:?}"
                ));
            }
            if phase_rank(phase) == phase_rank(prev_phase) {
                // INV-D4 idempotency at per-node granularity.
                return CommandResponse::Ok;
            }
        }
        alloc.per_node_phase.insert(node_id.clone(), phase);

        // DEC-DISP-11 aggregation:
        //   Staging  : any assigned node is Staging (or no report yet).
        //   Running  : ALL assigned nodes are Running or beyond.
        //   Completed: ALL assigned nodes are Completed with exit 0.
        //   Failed   : ANY assigned node is Failed, OR ALL are Completed
        //              but at least one had non-zero exit_code.
        let per_node = &alloc.per_node_phase;
        let all_assigned: &[NodeId] = &alloc.assigned_nodes;
        let any_failed = all_assigned
            .iter()
            .any(|n| per_node.get(n) == Some(&CompletionPhase::Failed));
        let all_have_report = all_assigned.iter().all(|n| per_node.contains_key(n));
        let all_running_plus = all_have_report
            && all_assigned.iter().all(|n| {
                matches!(
                    per_node.get(n),
                    Some(CompletionPhase::Running)
                        | Some(CompletionPhase::Completed)
                        | Some(CompletionPhase::Failed),
                )
            });
        let all_completed = all_have_report
            && all_assigned
                .iter()
                .all(|n| matches!(per_node.get(n), Some(CompletionPhase::Completed)));

        let exit_nonzero = exit_code.is_some() && exit_code != Some(0);
        let new_state = if any_failed {
            AllocationState::Failed
        } else if all_completed {
            if exit_nonzero {
                AllocationState::Failed
            } else {
                AllocationState::Completed
            }
        } else if all_running_plus {
            AllocationState::Running
        } else {
            AllocationState::Staging
        };
        alloc.state = new_state;
        alloc.last_completion_report_at = Some(Utc::now());
        if let Some(code) = exit_code {
            alloc.exit_code = Some(code);
        }
        if reason.is_some() {
            alloc.message = reason;
        }
        if pid.is_some() {
            // PID is agent-local; not surfaced in the quorum state machine
            // beyond acknowledging the transition.
        }
        match phase {
            CompletionPhase::Completed | CompletionPhase::Failed => {
                alloc.completed_at = Some(Utc::now());
            }
            CompletionPhase::Running if alloc.started_at.is_none() => {
                alloc.started_at = Some(Utc::now());
            }
            _ => {}
        }
        alloc.state_version += 1;

        // INV-D11 reset: a successful Staging/Running report is evidence
        // that dispatch worked on this node, so clear its failure counter.
        if matches!(phase, CompletionPhase::Staging | CompletionPhase::Running) {
            if let Some(node) = self.nodes.get_mut(&node_id) {
                node.consecutive_dispatch_failures = 0;
            }
        }

        CommandResponse::Ok
    }

    fn rollback_dispatch(
        &mut self,
        allocation_id: AllocId,
        released_nodes: Vec<NodeId>,
        failed_node: Option<NodeId>,
        observed_state_version: u64,
        reason: String,
    ) -> CommandResponse {
        let Some(alloc) = self.allocations.get_mut(&allocation_id) else {
            return CommandResponse::Error(format!("Allocation not found: {allocation_id}"));
        };

        // INV-D6 optimistic concurrency: reject if the allocation has
        // advanced since the dispatcher's observation.
        if alloc.state_version != observed_state_version {
            return CommandResponse::Error(format!(
                "state_version_mismatch: observed {observed_state_version}, current {}",
                alloc.state_version
            ));
        }

        const MAX_DISPATCH_RETRIES: u32 = 3;

        // Release all assigned nodes (DEC-DISP-07 all-or-nothing).
        for node_id in &released_nodes {
            if let Some(node) = self.nodes.get_mut(node_id) {
                if node.owner.as_ref().map(|o| o.allocation) == Some(allocation_id) {
                    node.owner = None;
                    node.owner_version += 1;
                }
            }
        }

        // Clear allocation's assigned_nodes, per-node phase tracking,
        // and increment retry counter. Per-node phase must be cleared so
        // the next dispatch attempt starts fresh aggregation.
        alloc.assigned_nodes.clear();
        alloc.per_node_phase.clear();
        alloc.assigned_at = None;
        alloc.dispatch_retry_count += 1;
        alloc.message = Some(reason);

        // Cap check: move to Failed if we've exhausted the retry budget,
        // otherwise return to Pending for re-placement.
        if alloc.dispatch_retry_count >= MAX_DISPATCH_RETRIES {
            alloc.state = AllocationState::Failed;
            alloc.completed_at = Some(Utc::now());
        } else {
            alloc.state = AllocationState::Pending;
            alloc.started_at = None;
        }
        alloc.state_version += 1;

        // INV-D11: credit the specific node whose dispatch failed.
        if let Some(node_id) = failed_node {
            if let Some(node) = self.nodes.get_mut(&node_id) {
                node.consecutive_dispatch_failures =
                    node.consecutive_dispatch_failures.saturating_add(1);
                // Degraded transition is subject to the cluster-wide guard
                // (DEC-DISP-01); simplified here: transition when the
                // node-level cap is reached.
                const MAX_NODE_DISPATCH_FAILURES: u32 = 5;
                if node.consecutive_dispatch_failures >= MAX_NODE_DISPATCH_FAILURES
                    && matches!(node.state, NodeState::Ready)
                {
                    lattice_common::metrics::record_node_degraded(&node_id);
                    node.state = NodeState::Degraded {
                        reason: "max_node_dispatch_failures".into(),
                    };
                    node.degraded_at = Some(Utc::now());
                }
            }
        }

        CommandResponse::Ok
    }

    fn probe_release_degraded_node(
        &mut self,
        node_id: NodeId,
        expected_degraded_at: DateTime<Utc>,
    ) -> CommandResponse {
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return CommandResponse::Error(format!("Node not found: {node_id}"));
        };
        // Version check: bail if the node has been degraded again since
        // the dispatcher observed the prior degraded_at timestamp.
        if node.degraded_at != Some(expected_degraded_at) {
            return CommandResponse::Error(format!(
                "degraded_at_mismatch: observed {expected_degraded_at}, current {:?}",
                node.degraded_at
            ));
        }
        if !matches!(node.state, NodeState::Degraded { .. }) {
            return CommandResponse::Error(format!("Node {node_id} is not Degraded"));
        }
        node.consecutive_dispatch_failures /= 2;
        node.state = NodeState::Ready;
        node.degraded_at = None;
        CommandResponse::Ok
    }

    // ── Tenant operations ───────────────────────────────────

    fn create_tenant(&mut self, tenant: Tenant) -> CommandResponse {
        let id = tenant.id.clone();
        self.tenants.insert(id.clone(), tenant);
        CommandResponse::TenantId(id)
    }

    fn update_tenant(
        &mut self,
        id: TenantId,
        quota: Option<TenantQuota>,
        isolation_level: Option<IsolationLevel>,
    ) -> CommandResponse {
        let Some(tenant) = self.tenants.get_mut(&id) else {
            return CommandResponse::Error(format!("Tenant not found: {id}"));
        };
        if let Some(q) = quota {
            tenant.quota = q;
        }
        if let Some(il) = isolation_level {
            tenant.isolation_level = il;
        }
        CommandResponse::Ok
    }

    // ── VCluster operations ─────────────────────────────────

    fn create_vcluster(&mut self, vc: VCluster) -> CommandResponse {
        let id = vc.id.clone();
        self.vclusters.insert(id.clone(), vc);
        CommandResponse::VClusterId(id)
    }

    fn update_vcluster(
        &mut self,
        id: VClusterId,
        cost_weights: Option<lattice_common::types::CostWeights>,
        allow_borrowing: Option<bool>,
        allow_lending: Option<bool>,
    ) -> CommandResponse {
        let Some(vc) = self.vclusters.get_mut(&id) else {
            return CommandResponse::Error(format!("VCluster not found: {id}"));
        };
        if let Some(cw) = cost_weights {
            vc.cost_weights = cw;
        }
        if let Some(b) = allow_borrowing {
            vc.allow_borrowing = b;
        }
        if let Some(l) = allow_lending {
            vc.allow_lending = l;
        }
        CommandResponse::Ok
    }

    // ── Network domain operations (ADV-08, ADV-09) ────────

    fn create_network_domain(&mut self, tenant: TenantId, name: String) -> CommandResponse {
        let domain_key = format!("{tenant}/{name}");
        if self.network_domains.contains_key(&domain_key) {
            return CommandResponse::Error(format!(
                "Network domain '{name}' already exists for tenant '{tenant}'"
            ));
        }
        let Some(vni) = self.vni_pool.allocate(&domain_key) else {
            return CommandResponse::Error("VNI pool exhausted".to_string());
        };
        let domain = NetworkDomain {
            name: name.clone(),
            tenant,
            vni,
            state: NetworkDomainState::Active,
            member_allocations: Vec::new(),
            created_at: Utc::now(),
            grace_deadline: None,
        };
        self.network_domains.insert(domain_key, domain);
        CommandResponse::Ok
    }

    fn release_network_domain(&mut self, tenant: TenantId, name: String) -> CommandResponse {
        let domain_key = format!("{tenant}/{name}");
        let Some(domain) = self.network_domains.get_mut(&domain_key) else {
            return CommandResponse::Error(format!(
                "Network domain '{name}' not found for tenant '{tenant}'"
            ));
        };
        let vni = domain.vni;
        domain.state = NetworkDomainState::Released;
        self.vni_pool.release(vni);
        CommandResponse::Ok
    }

    // ── Audit operations (ADV-03) ───────────────────────────

    fn record_audit(&mut self, mut entry: AuditEntry) -> CommandResponse {
        // Compute hash chain: previous_hash = SHA-256 of last entry.
        let previous_hash = if let Some(last) = self.audit_log.last() {
            Self::hash_audit_entry(last)
        } else {
            String::new()
        };
        entry.previous_hash = previous_hash;
        // Sign with ed25519 over the entry's canonical fields.
        entry.signature = self.sign_audit_entry(&entry);
        self.audit_log.push(entry);
        CommandResponse::Ok
    }

    /// Compute SHA-256 hash of an audit entry for chain linking.
    fn hash_audit_entry(entry: &AuditEntry) -> String {
        let mut hasher = Sha256::new();
        // Hash the serialized AuditEvent as canonical representation.
        let event_json = serde_json::to_string(&entry.event).unwrap_or_default();
        hasher.update(event_json.as_bytes());
        hasher.update(entry.previous_hash.as_bytes());
        let result = hasher.finalize();
        result.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// Canonical byte representation of an audit entry for signing/verification.
    fn canonical_bytes(entry: &AuditEntry) -> Vec<u8> {
        let mut buf = Vec::new();
        let event_json = serde_json::to_string(&entry.event).unwrap_or_default();
        buf.extend(event_json.as_bytes());
        buf.extend(entry.previous_hash.as_bytes());
        buf
    }

    /// Sign an audit entry with ed25519 using the node's signing key.
    fn sign_audit_entry(&self, entry: &AuditEntry) -> String {
        let canonical = Self::canonical_bytes(entry);
        let signature = self.audit_signing_key.sign(&canonical);
        hex::encode(signature.to_bytes())
    }

    /// Verify an audit entry's ed25519 signature against a verifying key.
    pub fn verify_audit_entry(entry: &AuditEntry, verifying_key: &VerifyingKey) -> bool {
        let canonical = Self::canonical_bytes(entry);
        let sig_bytes = match hex::decode(&entry.signature) {
            Ok(b) => b,
            Err(_) => return false,
        };
        let signature = match ed25519_dalek::Signature::from_slice(&sig_bytes) {
            Ok(s) => s,
            Err(_) => return false,
        };
        verifying_key.verify(&canonical, &signature).is_ok()
    }

    /// Verify the full audit chain: hash linkage and ed25519 signatures.
    pub fn verify_audit_chain(&self) -> Result<(), String> {
        let vk = self.audit_signing_key.verifying_key();
        for (i, entry) in self.audit_log.iter().enumerate() {
            // Verify hash chain
            let expected_prev = if i == 0 {
                String::new()
            } else {
                Self::hash_audit_entry(&self.audit_log[i - 1])
            };
            if entry.previous_hash != expected_prev {
                return Err(format!("Hash chain broken at entry {i}"));
            }
            // Verify signature
            if !Self::verify_audit_entry(entry, &vk) {
                return Err(format!("Invalid signature at entry {i}"));
            }
        }
        Ok(())
    }

    /// Set the ed25519 signing key (loaded from site configuration).
    pub fn set_signing_key(&mut self, key: SigningKey) {
        self.audit_signing_key = key;
    }

    /// Get the verifying (public) key corresponding to the current signing key.
    pub fn verifying_key(&self) -> VerifyingKey {
        self.audit_signing_key.verifying_key()
    }

    // ── Audit archival ───────────────────────────────────────

    /// Archive old audit entries by recording metadata and removing them from in-memory state.
    /// The caller must upload the entries to the given object_key before proposing this command.
    fn compact_audit_log(
        &mut self,
        object_key: String,
        entries_to_archive: usize,
    ) -> CommandResponse {
        if entries_to_archive == 0 || entries_to_archive > self.audit_log.len() {
            return CommandResponse::Error(format!(
                "Invalid archive count: {} (audit log has {} entries)",
                entries_to_archive,
                self.audit_log.len()
            ));
        }

        let first_timestamp = self.audit_log[0].event.timestamp;
        let last_entry = &self.audit_log[entries_to_archive - 1];
        let last_timestamp = last_entry.event.timestamp;
        let last_entry_hash = Self::hash_audit_entry(last_entry);

        let archive = AuditArchive {
            object_key,
            entry_count: entries_to_archive,
            first_timestamp,
            last_timestamp,
            last_entry_hash,
        };

        self.audit_archives.push(archive);
        self.audit_log = self.audit_log.split_off(entries_to_archive);

        CommandResponse::Ok
    }

    /// Whether any audit entries have been archived to external storage.
    pub fn has_archived_entries(&self) -> bool {
        !self.audit_archives.is_empty()
    }

    /// Get summaries of all archived audit log chunks.
    pub fn archive_summary(&self) -> &[AuditArchive] {
        &self.audit_archives
    }

    /// Total audit entry count including both in-memory and archived entries.
    pub fn total_audit_entry_count(&self) -> usize {
        let archived: usize = self.audit_archives.iter().map(|a| a.entry_count).sum();
        archived + self.audit_log.len()
    }

    // ── Quota enforcement ───────────────────────────────────

    /// Check hard quota limits before accepting an allocation.
    fn check_hard_quota(&self, alloc: &Allocation) -> Result<(), LatticeError> {
        let Some(tenant) = self.tenants.get(&alloc.tenant) else {
            // No tenant registered yet — allow (tenant may be created later)
            return Ok(());
        };

        // Check max_nodes quota using worst-case (max) for ranges
        let requested_nodes = match &alloc.resources.nodes {
            lattice_common::types::NodeCount::Exact(n) => *n,
            lattice_common::types::NodeCount::Range { max, .. } => *max,
        };
        let currently_used: u32 = self
            .allocations
            .values()
            .filter(|a| a.tenant == alloc.tenant && !a.state.is_terminal())
            .map(|a| a.assigned_nodes.len() as u32)
            .sum();

        if currently_used + requested_nodes > tenant.quota.max_nodes {
            return Err(LatticeError::QuotaExceeded {
                tenant: alloc.tenant.clone(),
                detail: format!(
                    "max_nodes quota ({}) would be exceeded: {} in use + {} requested",
                    tenant.quota.max_nodes, currently_used, requested_nodes
                ),
            });
        }

        // Check max_concurrent_allocations
        if let Some(max_concurrent) = tenant.quota.max_concurrent_allocations {
            let active_count = self
                .allocations
                .values()
                .filter(|a| a.tenant == alloc.tenant && !a.state.is_terminal())
                .count() as u32;

            if active_count >= max_concurrent {
                return Err(LatticeError::QuotaExceeded {
                    tenant: alloc.tenant.clone(),
                    detail: format!(
                        "max_concurrent_allocations quota ({}) reached: {} active",
                        max_concurrent, active_count
                    ),
                });
            }
        }

        Ok(())
    }
}

impl raft_hpc_core::StateMachineState<TypeConfig> for GlobalState {
    fn apply(&mut self, cmd: Command) -> CommandResponse {
        GlobalState::apply(self, cmd)
    }

    fn blank_response() -> CommandResponse {
        CommandResponse::Ok
    }
}

impl raft_hpc_core::BackupMetadataSource for GlobalState {
    type Metadata = LatticeBackupMeta;

    fn backup_metadata(&self) -> Self::Metadata {
        LatticeBackupMeta {
            node_count: self.nodes.len(),
            allocation_count: self.allocations.len(),
            tenant_count: self.tenants.len(),
            audit_entry_count: self.audit_log.len(),
            audit_archive_count: self.audit_archives.len(),
            total_audit_entries: self.total_audit_entry_count(),
        }
    }
}

/// Application-specific backup metadata for Lattice.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LatticeBackupMeta {
    pub node_count: usize,
    pub allocation_count: usize,
    pub tenant_count: usize,
    pub audit_entry_count: usize,
    #[serde(default)]
    pub audit_archive_count: usize,
    #[serde(default)]
    pub total_audit_entries: usize,
}

impl GlobalState {
    // ── Query helpers ───────────────────────────────────────

    pub fn query_audit(&self, filter: &AuditFilter) -> Vec<AuditEntry> {
        self.audit_log
            .iter()
            .filter(|e| {
                if let Some(ref principal) = filter.principal {
                    if &e.event.principal.identity != principal {
                        return false;
                    }
                }
                if let Some(ref action) = filter.action {
                    if &e.event.action != action {
                        return false;
                    }
                }
                if let Some(ref alloc) = filter.allocation {
                    let alloc_str = alloc.to_string();
                    if e.event.scope.allocation_id.as_deref() != Some(alloc_str.as_str()) {
                        return false;
                    }
                }
                if let Some(ref since) = filter.since {
                    if e.event.timestamp < *since {
                        return false;
                    }
                }
                if let Some(ref until) = filter.until {
                    if e.event.timestamp > *until {
                        return false;
                    }
                }
                true
            })
            .cloned()
            .collect()
    }

    /// Look up registered endpoints for a named service.
    pub fn lookup_service(&self, name: &str) -> Option<&ServiceRegistryEntry> {
        self.service_registry.get(name)
    }

    /// List all registered service names.
    pub fn list_services(&self) -> Vec<String> {
        self.service_registry.keys().cloned().collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lattice_common::traits::{audit_actions, lattice_audit_event};
    use lattice_common::types::{AllocationState, NodeOwnership, NodeState, TenantQuota};
    use lattice_test_harness::fixtures::{
        AllocationBuilder, NodeBuilder, TenantBuilder, VClusterBuilder,
    };
    use uuid::Uuid;

    fn test_allocation(tenant: &str) -> Allocation {
        AllocationBuilder::new().tenant(tenant).build()
    }

    fn test_node(id: &str) -> Node {
        NodeBuilder::new().id(id).build()
    }

    #[test]
    fn submit_allocation_stores_it() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        let resp = state.apply(Command::SubmitAllocation(alloc));
        assert!(matches!(resp, CommandResponse::AllocationId(aid) if aid == id));
        assert!(state.allocations.contains_key(&id));
    }

    #[test]
    fn update_allocation_state_valid_transition() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        let resp = state.apply(Command::UpdateAllocationState {
            id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });
        assert!(matches!(resp, CommandResponse::Ok));
        assert_eq!(state.allocations[&id].state, AllocationState::Running);
        assert!(state.allocations[&id].started_at.is_some());
    }

    #[test]
    fn update_allocation_state_invalid_transition() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        let resp = state.apply(Command::UpdateAllocationState {
            id,
            state: AllocationState::Completed,
            message: None,
            exit_code: None,
        });
        assert!(matches!(resp, CommandResponse::Error(_)));
    }

    #[test]
    fn register_and_claim_node() {
        let mut state = GlobalState::new();
        let node = test_node("x1000c0s0b0n0");
        state.apply(Command::RegisterNode(node));

        let ownership = NodeOwnership {
            tenant: "med-tenant".into(),
            vcluster: "med-vc".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("dr-smith".into()),
            is_borrowed: false,
        };
        let resp = state.apply(Command::ClaimNode {
            id: "x1000c0s0b0n0".into(),
            ownership,
        });
        assert!(matches!(resp, CommandResponse::Ok));

        let node = &state.nodes["x1000c0s0b0n0"];
        assert!(node.owner.is_some());
        assert_eq!(
            node.owner.as_ref().unwrap().claimed_by.as_deref(),
            Some("dr-smith")
        );
    }

    #[test]
    fn claim_conflict_detected() {
        let mut state = GlobalState::new();
        let node = test_node("x1000c0s0b0n0");
        state.apply(Command::RegisterNode(node));

        let ownership1 = NodeOwnership {
            tenant: "tenant-1".into(),
            vcluster: "vc-1".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-1".into()),
            is_borrowed: false,
        };
        state.apply(Command::ClaimNode {
            id: "x1000c0s0b0n0".into(),
            ownership: ownership1,
        });

        let ownership2 = NodeOwnership {
            tenant: "tenant-2".into(),
            vcluster: "vc-2".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-2".into()),
            is_borrowed: false,
        };
        let resp = state.apply(Command::ClaimNode {
            id: "x1000c0s0b0n0".into(),
            ownership: ownership2,
        });
        assert!(matches!(resp, CommandResponse::Error(_)));
    }

    #[test]
    fn release_node_clears_ownership() {
        let mut state = GlobalState::new();
        let node = test_node("x1000c0s0b0n0");
        state.apply(Command::RegisterNode(node));

        let ownership = NodeOwnership {
            tenant: "tenant-1".into(),
            vcluster: "vc-1".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-1".into()),
            is_borrowed: false,
        };
        state.apply(Command::ClaimNode {
            id: "x1000c0s0b0n0".into(),
            ownership,
        });

        state.apply(Command::ReleaseNode {
            id: "x1000c0s0b0n0".into(),
        });
        assert!(state.nodes["x1000c0s0b0n0"].owner.is_none());
    }

    #[test]
    fn sensitive_pool_size_limits_claims() {
        let mut state = GlobalState::new();
        state.apply(Command::SetSensitivePoolSize(Some(1)));
        state.apply(Command::RegisterNode(test_node("n1")));
        state.apply(Command::RegisterNode(test_node("n2")));

        let ownership1 = NodeOwnership {
            tenant: "t1".into(),
            vcluster: "vc1".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-1".into()),
            is_borrowed: false,
        };
        let resp = state.apply(Command::ClaimNode {
            id: "n1".into(),
            ownership: ownership1,
        });
        assert!(matches!(resp, CommandResponse::Ok));

        // Second sensitive claim should be rejected (pool_size=1)
        let ownership2 = NodeOwnership {
            tenant: "t2".into(),
            vcluster: "vc2".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-2".into()),
            is_borrowed: false,
        };
        let resp = state.apply(Command::ClaimNode {
            id: "n2".into(),
            ownership: ownership2,
        });
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("sensitive_pool_size")));
    }

    #[test]
    fn sensitive_pool_unlimited_by_default() {
        let mut state = GlobalState::new();
        // No pool size set → unlimited
        state.apply(Command::RegisterNode(test_node("n1")));
        state.apply(Command::RegisterNode(test_node("n2")));

        for (node_id, user) in [("n1", "user-1"), ("n2", "user-2")] {
            let ownership = NodeOwnership {
                tenant: "t1".into(),
                vcluster: "vc1".into(),
                allocation: Uuid::new_v4(),
                claimed_by: Some(user.into()),
                is_borrowed: false,
            };
            let resp = state.apply(Command::ClaimNode {
                id: node_id.into(),
                ownership,
            });
            assert!(matches!(resp, CommandResponse::Ok));
        }
    }

    #[test]
    fn non_sensitive_claim_bypasses_pool_limit() {
        let mut state = GlobalState::new();
        state.apply(Command::SetSensitivePoolSize(Some(0)));
        state.apply(Command::RegisterNode(test_node("n1")));

        // Non-sensitive claim (claimed_by is None) should still work
        let ownership = NodeOwnership {
            tenant: "t1".into(),
            vcluster: "vc1".into(),
            allocation: Uuid::new_v4(),
            claimed_by: None,
            is_borrowed: false,
        };
        let resp = state.apply(Command::ClaimNode {
            id: "n1".into(),
            ownership,
        });
        assert!(matches!(resp, CommandResponse::Ok));
    }

    #[test]
    fn hard_quota_blocks_over_limit() {
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("limited").max_nodes(2).build();
        state.apply(Command::CreateTenant(tenant));

        // Submit allocation requesting 1 node, assign 2 nodes
        let mut alloc1 = test_allocation("limited");
        alloc1.assigned_nodes = vec!["n1".into(), "n2".into()];
        alloc1.state = AllocationState::Running;
        state.allocations.insert(alloc1.id, alloc1);

        // Try to submit another — quota exceeded
        let alloc2 = test_allocation("limited");
        let resp = state.apply(Command::SubmitAllocation(alloc2));
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("max_nodes")));
    }

    #[test]
    fn concurrent_allocation_limit() {
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("limited")
            .max_nodes(100)
            .max_concurrent(2)
            .build();
        state.apply(Command::CreateTenant(tenant));

        // Submit 2 allocations
        state.apply(Command::SubmitAllocation(test_allocation("limited")));
        state.apply(Command::SubmitAllocation(test_allocation("limited")));

        // Third should fail
        let resp = state.apply(Command::SubmitAllocation(test_allocation("limited")));
        assert!(
            matches!(resp, CommandResponse::Error(e) if e.contains("max_concurrent_allocations"))
        );
    }

    #[test]
    fn audit_log_append_and_query() {
        let mut state = GlobalState::new();
        let entry = AuditEntry::new(lattice_audit_event(
            audit_actions::NODE_CLAIM,
            "dr-smith",
            hpc_audit::AuditScope::default(),
            hpc_audit::AuditOutcome::Success,
            "node claim",
            serde_json::json!({"node": "x1000c0s0b0n0"}),
            hpc_audit::AuditSource::LatticeQuorum,
        ));
        state.apply(Command::RecordAudit(entry.clone()));

        let results = state.query_audit(&AuditFilter {
            principal: Some("dr-smith".into()),
            ..Default::default()
        });
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].event.action, audit_actions::NODE_CLAIM);
        // ADV-03: verify hash chain and signature are populated
        assert!(!results[0].signature.is_empty());
        // First entry has empty previous_hash
        assert!(results[0].previous_hash.is_empty());
        // Verify ed25519 signature
        let vk = state.verifying_key();
        assert!(GlobalState::verify_audit_entry(&results[0], &vk));
    }

    #[test]
    fn audit_hash_chain_links_entries() {
        let mut state = GlobalState::new();
        let entry1 = AuditEntry::new(lattice_audit_event(
            audit_actions::NODE_CLAIM,
            "user-1",
            hpc_audit::AuditScope::default(),
            hpc_audit::AuditOutcome::Success,
            "node claim",
            serde_json::json!({}),
            hpc_audit::AuditSource::LatticeQuorum,
        ));
        state.apply(Command::RecordAudit(entry1));

        let entry2 = AuditEntry::new(lattice_audit_event(
            audit_actions::NODE_RELEASE,
            "user-2",
            hpc_audit::AuditScope::default(),
            hpc_audit::AuditOutcome::Success,
            "node release",
            serde_json::json!({}),
            hpc_audit::AuditSource::LatticeQuorum,
        ));
        state.apply(Command::RecordAudit(entry2));

        assert_eq!(state.audit_log.len(), 2);
        // Second entry's previous_hash should reference first entry
        assert!(!state.audit_log[1].previous_hash.is_empty());
        assert!(!state.audit_log[1].signature.is_empty());
        // Hash chain is consistent
        let expected_hash = GlobalState::hash_audit_entry(&state.audit_log[0]);
        assert_eq!(state.audit_log[1].previous_hash, expected_hash);
        // Full chain verification passes
        assert!(state.verify_audit_chain().is_ok());
    }

    #[test]
    fn audit_signature_verification() {
        let mut state = GlobalState::new();
        let entry = AuditEntry::new(lattice_audit_event(
            audit_actions::DATA_ACCESS,
            "user-1",
            hpc_audit::AuditScope::default(),
            hpc_audit::AuditOutcome::Success,
            "data access",
            serde_json::json!({"file": "/data/sensitive.csv"}),
            hpc_audit::AuditSource::LatticeQuorum,
        ));
        state.apply(Command::RecordAudit(entry));

        let vk = state.verifying_key();
        // Valid signature passes
        assert!(GlobalState::verify_audit_entry(&state.audit_log[0], &vk));

        // Tamper with the entry and verify it fails
        let mut tampered = state.audit_log[0].clone();
        tampered.event.principal.identity = "attacker".into();
        assert!(!GlobalState::verify_audit_entry(&tampered, &vk));

        // Invalid hex signature fails gracefully
        let mut bad_sig = state.audit_log[0].clone();
        bad_sig.signature = "not-valid-hex!".into();
        assert!(!GlobalState::verify_audit_entry(&bad_sig, &vk));

        // Wrong-length signature fails gracefully
        let mut short_sig = state.audit_log[0].clone();
        short_sig.signature = "abcd".into();
        assert!(!GlobalState::verify_audit_entry(&short_sig, &vk));

        // Verify with a different key fails
        let other_key = SigningKey::generate(&mut rand_core::OsRng);
        let other_vk = other_key.verifying_key();
        assert!(!GlobalState::verify_audit_entry(
            &state.audit_log[0],
            &other_vk
        ));
    }

    #[test]
    fn audit_chain_integrity_full() {
        let mut state = GlobalState::new();
        let actions = [
            audit_actions::NODE_CLAIM,
            audit_actions::ALLOCATION_START,
            audit_actions::DATA_ACCESS,
            audit_actions::METRICS_QUERY,
            audit_actions::CHECKPOINT_TRIGGERED,
            audit_actions::LOG_ACCESS,
            audit_actions::ATTACH_SESSION,
            audit_actions::ALLOCATION_COMPLETE,
            audit_actions::NODE_RELEASE,
            audit_actions::WIPE_COMPLETED,
        ];
        for (i, action) in actions.iter().enumerate() {
            let entry = AuditEntry::new(lattice_audit_event(
                action,
                &format!("user-{i}"),
                hpc_audit::AuditScope::default(),
                hpc_audit::AuditOutcome::Success,
                "chain test",
                serde_json::json!({"step": i}),
                hpc_audit::AuditSource::LatticeQuorum,
            ));
            state.apply(Command::RecordAudit(entry));
        }

        assert_eq!(state.audit_log.len(), 10);
        // Full chain verification passes
        assert!(state.verify_audit_chain().is_ok());

        // Tamper with an entry in the middle — chain should break
        state.audit_log[5].event.metadata = serde_json::json!({"tampered": true});
        let result = state.verify_audit_chain();
        assert!(result.is_err());
        // Should report the tampered entry's signature failure
        assert!(result.unwrap_err().contains("Invalid signature at entry 5"));
    }

    #[test]
    fn state_version_increments_on_mutation() {
        let mut state = GlobalState::new();
        assert_eq!(state.state_version, 0);
        state.apply(Command::RegisterNode(test_node("n1")));
        assert_eq!(state.state_version, 1);
        state.apply(Command::RegisterNode(test_node("n2")));
        assert_eq!(state.state_version, 2);
    }

    #[test]
    fn stale_assign_nodes_rejected() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        let version_at_submit = state.state_version;

        // Another mutation changes the version
        state.apply(Command::RegisterNode(test_node("n1")));
        assert!(state.state_version > version_at_submit);

        // Stale proposal with old version is rejected
        let resp = state.apply(Command::AssignNodes {
            id,
            nodes: vec!["n1".into()],
            expected_version: Some(version_at_submit),
        });
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("Stale proposal")));
    }

    #[test]
    fn heartbeat_with_stale_owner_version_rejected() {
        let mut state = GlobalState::new();
        state.apply(Command::RegisterNode(test_node("n1")));

        // Claim the node (bumps owner_version to 1)
        let ownership = NodeOwnership {
            tenant: "t1".into(),
            vcluster: "vc1".into(),
            allocation: Uuid::new_v4(),
            claimed_by: Some("user-1".into()),
            is_borrowed: false,
        };
        state.apply(Command::ClaimNode {
            id: "n1".into(),
            ownership,
        });
        assert_eq!(state.nodes["n1"].owner_version, 1);

        // Heartbeat with old version 0 is rejected
        let resp = state.apply(Command::RecordHeartbeat {
            id: "n1".into(),
            timestamp: Utc::now(),
            owner_version: 0,
            reattach_in_progress: false,
        });
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("Stale heartbeat")));

        // Heartbeat with correct version 1 is accepted
        let ts = Utc::now();
        let resp = state.apply(Command::RecordHeartbeat {
            id: "n1".into(),
            timestamp: ts,
            owner_version: 1,
            reattach_in_progress: false,
        });
        assert!(matches!(resp, CommandResponse::Ok));
        assert_eq!(state.nodes["n1"].last_heartbeat, Some(ts));
    }

    #[test]
    fn create_and_release_network_domain() {
        let mut state = GlobalState::new();
        let resp = state.apply(Command::CreateNetworkDomain {
            tenant: "t1".into(),
            name: "my-domain".into(),
        });
        assert!(matches!(resp, CommandResponse::Ok));
        assert!(state.network_domains.contains_key("t1/my-domain"));
        let domain = &state.network_domains["t1/my-domain"];
        assert_eq!(domain.state, NetworkDomainState::Active);
        assert!(domain.vni >= 100);

        // Duplicate creation fails
        let resp = state.apply(Command::CreateNetworkDomain {
            tenant: "t1".into(),
            name: "my-domain".into(),
        });
        assert!(matches!(resp, CommandResponse::Error(_)));

        // Different tenant same name succeeds (ADV-09: tenant-scoped)
        let resp = state.apply(Command::CreateNetworkDomain {
            tenant: "t2".into(),
            name: "my-domain".into(),
        });
        assert!(matches!(resp, CommandResponse::Ok));

        // Release
        let resp = state.apply(Command::ReleaseNetworkDomain {
            tenant: "t1".into(),
            name: "my-domain".into(),
        });
        assert!(matches!(resp, CommandResponse::Ok));
        assert_eq!(
            state.network_domains["t1/my-domain"].state,
            NetworkDomainState::Released
        );
    }

    #[test]
    fn node_state_transition_validated() {
        let mut state = GlobalState::new();
        state.apply(Command::RegisterNode(test_node("n1")));

        // Ready → Draining is valid
        let resp = state.apply(Command::UpdateNodeState {
            id: "n1".into(),
            state: NodeState::Draining,
            reason: Some("maintenance".into()),
        });
        assert!(matches!(resp, CommandResponse::Ok));

        // Draining → Ready is invalid
        let resp = state.apply(Command::UpdateNodeState {
            id: "n1".into(),
            state: NodeState::Ready,
            reason: None,
        });
        assert!(matches!(resp, CommandResponse::Error(_)));
    }

    #[test]
    fn heartbeat_updates_timestamp() {
        let mut state = GlobalState::new();
        state.apply(Command::RegisterNode(test_node("n1")));

        let ts = Utc::now();
        state.apply(Command::RecordHeartbeat {
            id: "n1".into(),
            timestamp: ts,
            owner_version: 0, // matches initial version
            reattach_in_progress: false,
        });

        assert_eq!(state.nodes["n1"].last_heartbeat, Some(ts));
    }

    #[test]
    fn create_and_update_tenant() {
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("test-tenant").build();
        let tenant_id = tenant.id.clone();
        state.apply(Command::CreateTenant(tenant));

        state.apply(Command::UpdateTenant {
            id: tenant_id.clone(),
            quota: Some(TenantQuota {
                max_nodes: 20,
                fair_share_target: 0.2,
                gpu_hours_budget: None,
                node_hours_budget: None,
                max_concurrent_allocations: None,
                burst_allowance: None,
            }),
            isolation_level: None,
        });

        assert_eq!(state.tenants[&tenant_id].quota.max_nodes, 20);
    }

    #[test]
    fn create_and_update_vcluster() {
        let mut state = GlobalState::new();
        let vc = VClusterBuilder::new("vc-1").build();
        let vc_id = vc.id.clone();
        state.apply(Command::CreateVCluster(vc));

        state.apply(Command::UpdateVCluster {
            id: vc_id.clone(),
            cost_weights: None,
            allow_borrowing: Some(false),
            allow_lending: None,
        });

        assert!(!state.vclusters[&vc_id].allow_borrowing);
    }

    #[test]
    fn completed_allocation_sets_timestamp() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        state.apply(Command::UpdateAllocationState {
            id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        state.apply(Command::UpdateAllocationState {
            id,
            state: AllocationState::Completed,
            message: Some("done".into()),
            exit_code: Some(0),
        });

        let a = &state.allocations[&id];
        assert!(a.completed_at.is_some());
        assert_eq!(a.exit_code, Some(0));
        assert_eq!(a.message.as_deref(), Some("done"));
    }

    #[test]
    fn assign_nodes_to_allocation() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        state.apply(Command::AssignNodes {
            id,
            nodes: vec!["n1".into(), "n2".into()],
            expected_version: None,
        });

        assert_eq!(state.allocations[&id].assigned_nodes, vec!["n1", "n2"]);
    }

    #[test]
    fn assign_nodes_checks_tenant_quota() {
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("t1").max_nodes(3).build();
        state.apply(Command::CreateTenant(tenant));

        // First allocation: assign 2 nodes
        let alloc1 = AllocationBuilder::new().tenant("t1").build();
        let id1 = alloc1.id;
        state.apply(Command::SubmitAllocation(alloc1));
        state.apply(Command::AssignNodes {
            id: id1,
            nodes: vec!["n1".into(), "n2".into()],
            expected_version: None,
        });

        // Second allocation: assigning 2 more would exceed quota of 3
        let alloc2 = AllocationBuilder::new().tenant("t1").build();
        let id2 = alloc2.id;
        state.apply(Command::SubmitAllocation(alloc2));
        let resp = state.apply(Command::AssignNodes {
            id: id2,
            nodes: vec!["n3".into(), "n4".into()],
            expected_version: None,
        });
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("max_nodes")));
        // Original assignment unchanged
        assert!(state.allocations[&id2].assigned_nodes.is_empty());
    }

    #[test]
    fn submit_with_range_checks_max_not_min() {
        use lattice_common::types::NodeCount;
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("t1").max_nodes(5).build();
        state.apply(Command::CreateTenant(tenant));

        // Submit with range min=1, max=10 — should be rejected because max(10) > quota(5)
        let mut alloc = AllocationBuilder::new().tenant("t1").build();
        alloc.resources.nodes = NodeCount::Range { min: 1, max: 10 };
        let resp = state.apply(Command::SubmitAllocation(alloc));
        assert!(matches!(resp, CommandResponse::Error(e) if e.contains("max_nodes")));
    }

    #[test]
    fn assign_nodes_within_quota_succeeds() {
        let mut state = GlobalState::new();
        let tenant = TenantBuilder::new("t1").max_nodes(5).build();
        state.apply(Command::CreateTenant(tenant));

        let alloc = AllocationBuilder::new().tenant("t1").build();
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        let resp = state.apply(Command::AssignNodes {
            id,
            nodes: vec!["n1".into(), "n2".into(), "n3".into()],
            expected_version: None,
        });
        assert!(matches!(resp, CommandResponse::Ok));
        assert_eq!(state.allocations[&id].assigned_nodes.len(), 3);
    }

    // ── Audit archival tests ────────────────────────────────

    fn add_audit_entries(state: &mut GlobalState, count: usize) {
        for i in 0..count {
            let entry = AuditEntry::new(lattice_audit_event(
                audit_actions::DATA_ACCESS,
                &format!("user-{i}"),
                hpc_audit::AuditScope::default(),
                hpc_audit::AuditOutcome::Success,
                "data access",
                serde_json::json!({"index": i}),
                hpc_audit::AuditSource::LatticeQuorum,
            ));
            state.apply(Command::RecordAudit(entry));
        }
    }

    #[test]
    fn audit_compact_removes_old_entries() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 20);
        assert_eq!(state.audit_log.len(), 20);

        let resp = state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-001.json".into(),
            entries_to_archive: 15,
        });
        assert!(matches!(resp, CommandResponse::Ok));

        // 5 entries remain in-memory
        assert_eq!(state.audit_log.len(), 5);
        // 1 archive record created
        assert_eq!(state.audit_archives.len(), 1);
        assert_eq!(state.audit_archives[0].entry_count, 15);
        assert_eq!(
            state.audit_archives[0].object_key,
            "s3://audit/chunk-001.json"
        );
    }

    #[test]
    fn audit_compact_preserves_chain() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 10);

        // Compact first 7 entries
        state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-001.json".into(),
            entries_to_archive: 7,
        });
        assert_eq!(state.audit_log.len(), 3);

        // Add a new entry — its previous_hash should reference the last in-memory entry
        let new_entry = AuditEntry::new(lattice_audit_event(
            audit_actions::NODE_CLAIM,
            "user-new",
            hpc_audit::AuditScope::default(),
            hpc_audit::AuditOutcome::Success,
            "node claim",
            serde_json::json!({}),
            hpc_audit::AuditSource::LatticeQuorum,
        ));
        state.apply(Command::RecordAudit(new_entry));

        assert_eq!(state.audit_log.len(), 4);
        // The new entry's previous_hash should match the hash of the last remaining entry before it
        let expected_hash = GlobalState::hash_audit_entry(&state.audit_log[2]);
        assert_eq!(state.audit_log[3].previous_hash, expected_hash);
    }

    #[test]
    fn audit_archive_metadata_correct() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 10);

        let first_ts = state.audit_log[0].event.timestamp;
        let last_archived_ts = state.audit_log[4].event.timestamp;
        let last_archived_hash = GlobalState::hash_audit_entry(&state.audit_log[4]);

        state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-001.json".into(),
            entries_to_archive: 5,
        });

        let archive = &state.audit_archives[0];
        assert_eq!(archive.first_timestamp, first_ts);
        assert_eq!(archive.last_timestamp, last_archived_ts);
        assert_eq!(archive.last_entry_hash, last_archived_hash);
        assert_eq!(archive.entry_count, 5);
    }

    #[test]
    fn audit_total_count_includes_archives() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 20);

        state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-001.json".into(),
            entries_to_archive: 12,
        });

        assert_eq!(state.audit_log.len(), 8);
        assert_eq!(state.total_audit_entry_count(), 20);
        assert!(state.has_archived_entries());
        assert_eq!(state.archive_summary().len(), 1);
    }

    #[test]
    fn audit_compact_invalid_count_rejected() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 5);

        // Zero entries
        let resp = state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk.json".into(),
            entries_to_archive: 0,
        });
        assert!(matches!(resp, CommandResponse::Error(_)));

        // More than available
        let resp = state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk.json".into(),
            entries_to_archive: 10,
        });
        assert!(matches!(resp, CommandResponse::Error(_)));

        // Nothing should have changed
        assert_eq!(state.audit_log.len(), 5);
        assert!(state.audit_archives.is_empty());
    }

    #[test]
    fn audit_multiple_compactions() {
        let mut state = GlobalState::new();
        add_audit_entries(&mut state, 30);

        // First compaction
        state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-001.json".into(),
            entries_to_archive: 10,
        });
        assert_eq!(state.audit_log.len(), 20);
        assert_eq!(state.audit_archives.len(), 1);

        // Second compaction
        state.apply(Command::CompactAuditLog {
            object_key: "s3://audit/chunk-002.json".into(),
            entries_to_archive: 10,
        });
        assert_eq!(state.audit_log.len(), 10);
        assert_eq!(state.audit_archives.len(), 2);
        assert_eq!(state.total_audit_entry_count(), 30);
    }

    // ─── Service Registry tests ──────────────────────────────

    fn service_allocation(tenant: &str) -> Allocation {
        AllocationBuilder::new()
            .tenant(tenant)
            .lifecycle_unbounded()
            .connectivity(lattice_common::types::Connectivity {
                network_domain: None,
                expose: vec![lattice_common::types::ServiceEndpoint {
                    name: "inference-api".into(),
                    port: 8080,
                    protocol: Some("http".into()),
                }],
            })
            .build()
    }

    #[test]
    fn endpoints_registered_on_running() {
        let mut state = GlobalState::new();
        state
            .tenants
            .insert("t1".into(), TenantBuilder::new("t1").max_nodes(10).build());

        let alloc = service_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::AssignNodes {
            id: alloc_id,
            nodes: vec!["node-1".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        let entry = state.lookup_service("inference-api").unwrap();
        assert_eq!(entry.endpoints.len(), 1);
        assert_eq!(entry.endpoints[0].allocation_id, alloc_id);
        assert_eq!(entry.endpoints[0].port, 8080);
        assert_eq!(entry.endpoints[0].nodes, vec!["node-1".to_string()]);
    }

    #[test]
    fn endpoints_deregistered_on_completion() {
        let mut state = GlobalState::new();
        state
            .tenants
            .insert("t1".into(), TenantBuilder::new("t1").max_nodes(10).build());

        let alloc = service_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::AssignNodes {
            id: alloc_id,
            nodes: vec!["node-1".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        assert!(state.lookup_service("inference-api").is_some());

        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Completed,
            message: None,
            exit_code: Some(0),
        });

        assert!(state.lookup_service("inference-api").is_none());
    }

    #[test]
    fn endpoints_deregistered_on_requeue() {
        let mut state = GlobalState::new();
        state
            .tenants
            .insert("t1".into(), TenantBuilder::new("t1").max_nodes(10).build());

        let alloc = service_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::AssignNodes {
            id: alloc_id,
            nodes: vec!["node-1".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });
        // Mark failed (so it can be requeued)
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Failed,
            message: Some("node failure".into()),
            exit_code: None,
        });

        // Endpoints removed on failure
        assert!(state.lookup_service("inference-api").is_none());

        // Requeue
        state.apply(Command::RequeueAllocation {
            id: alloc_id,
            expected_requeue_count: None,
        });
        let alloc = state.allocations.get(&alloc_id).unwrap();
        assert_eq!(alloc.state, AllocationState::Pending);
        assert_eq!(alloc.requeue_count, 1);
    }

    #[test]
    fn multiple_allocations_same_service() {
        let mut state = GlobalState::new();
        state
            .tenants
            .insert("t1".into(), TenantBuilder::new("t1").max_nodes(10).build());

        let a1 = service_allocation("t1");
        let a2 = service_allocation("t1");
        let id1 = a1.id;
        let id2 = a2.id;

        // Submit and run both
        state.apply(Command::SubmitAllocation(a1));
        state.apply(Command::AssignNodes {
            id: id1,
            nodes: vec!["node-1".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: id1,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        state.apply(Command::SubmitAllocation(a2));
        state.apply(Command::AssignNodes {
            id: id2,
            nodes: vec!["node-2".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: id2,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        let entry = state.lookup_service("inference-api").unwrap();
        assert_eq!(entry.endpoints.len(), 2);

        // Complete one, other stays
        state.apply(Command::UpdateAllocationState {
            id: id1,
            state: AllocationState::Completed,
            message: None,
            exit_code: Some(0),
        });

        let entry = state.lookup_service("inference-api").unwrap();
        assert_eq!(entry.endpoints.len(), 1);
        assert_eq!(entry.endpoints[0].allocation_id, id2);
    }

    #[test]
    fn list_services_returns_registered() {
        let mut state = GlobalState::new();
        state
            .tenants
            .insert("t1".into(), TenantBuilder::new("t1").max_nodes(10).build());

        assert!(state.list_services().is_empty());

        let alloc = service_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::AssignNodes {
            id: alloc_id,
            nodes: vec!["node-1".into()],
            expected_version: None,
        });
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        let services = state.list_services();
        assert_eq!(services, vec!["inference-api"]);
    }

    #[test]
    fn resolve_image_updates_sha256() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        // The test allocation has one image by default
        let resolved = lattice_common::types::ImageRef {
            spec: "prgenv-gnu/24.11:v1".into(),
            image_type: lattice_common::types::ImageType::Uenv,
            registry: "jfrog.cscs.ch/uenv".into(),
            name: "prgenv-gnu".into(),
            version: "24.11".into(),
            sha256: "sha256:abc123def456".into(),
            size_bytes: 1_000_000,
            ..Default::default()
        };

        let resp = state.apply(Command::ResolveImage {
            id,
            image_index: 0,
            resolved,
        });
        assert!(matches!(resp, CommandResponse::Ok));

        let updated = &state.allocations[&id].environment.images[0];
        assert_eq!(updated.sha256, "sha256:abc123def456");
        assert_eq!(updated.size_bytes, 1_000_000);
        assert_eq!(updated.registry, "jfrog.cscs.ch/uenv");
        assert!(!updated.resolve_on_schedule);
    }

    #[test]
    fn resolve_image_invalid_index_returns_error() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("test-tenant");
        let id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));

        let resolved = lattice_common::types::ImageRef::default();
        let resp = state.apply(Command::ResolveImage {
            id,
            image_index: 99,
            resolved,
        });
        assert!(matches!(resp, CommandResponse::Error(ref e) if e.contains("out of bounds")));
    }

    #[test]
    fn resolve_image_nonexistent_allocation_returns_error() {
        let mut state = GlobalState::new();
        let resolved = lattice_common::types::ImageRef::default();
        let resp = state.apply(Command::ResolveImage {
            id: Uuid::new_v4(),
            image_index: 0,
            resolved,
        });
        assert!(matches!(resp, CommandResponse::Error(ref e) if e.contains("not found")));
    }

    // ── Session lifecycle tests ──

    #[test]
    fn session_create_and_delete() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        let session = Session {
            id: Uuid::new_v4(),
            allocation_id: alloc_id,
            user: "alice".into(),
            created_at: Utc::now(),
        };
        let sid = session.id;

        let resp = state.apply(Command::CreateSession(session));
        assert!(
            matches!(resp, CommandResponse::SessionId(id) if id == sid),
            "expected SessionId, got {resp:?}"
        );
        assert!(state.sessions.contains_key(&sid));

        let resp = state.apply(Command::DeleteSession { session_id: sid });
        assert!(matches!(resp, CommandResponse::Ok));
        assert!(!state.sessions.contains_key(&sid));
    }

    #[test]
    fn session_create_on_non_running_rejected() {
        let mut state = GlobalState::new();
        let alloc = test_allocation("t1");
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        // allocation is Pending, not Running

        let session = Session {
            id: Uuid::new_v4(),
            allocation_id: alloc_id,
            user: "alice".into(),
            created_at: Utc::now(),
        };

        let resp = state.apply(Command::CreateSession(session));
        assert!(matches!(resp, CommandResponse::Error(_)));
    }

    #[test]
    fn sensitive_allocation_single_session_enforced() {
        let mut state = GlobalState::new();
        let mut alloc = test_allocation("t1");
        alloc.sensitive = true;
        let alloc_id = alloc.id;
        state.apply(Command::SubmitAllocation(alloc));
        state.apply(Command::UpdateAllocationState {
            id: alloc_id,
            state: AllocationState::Running,
            message: None,
            exit_code: None,
        });

        // First session — should succeed
        let s1 = Session {
            id: Uuid::new_v4(),
            allocation_id: alloc_id,
            user: "alice".into(),
            created_at: Utc::now(),
        };
        let resp = state.apply(Command::CreateSession(s1));
        assert!(matches!(resp, CommandResponse::SessionId(_)));

        // Second session on same sensitive allocation — should be rejected (INV-C2)
        let s2 = Session {
            id: Uuid::new_v4(),
            allocation_id: alloc_id,
            user: "bob".into(),
            created_at: Utc::now(),
        };
        let resp = state.apply(Command::CreateSession(s2));
        assert!(
            matches!(resp, CommandResponse::Error(ref e) if e.contains("INV-C2")),
            "expected INV-C2 rejection, got {resp:?}"
        );
    }

    #[test]
    fn delete_nonexistent_session_returns_error() {
        let mut state = GlobalState::new();
        let resp = state.apply(Command::DeleteSession {
            session_id: Uuid::new_v4(),
        });
        assert!(matches!(resp, CommandResponse::Error(_)));
    }
}
