version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      rust-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
    rebase-strategy: auto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    rebase-strategy: auto
